# Multiple Linear Regression by sklearn

www.m-fozouni.ir

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
import seaborn as sns
sns.set()

## Load the data

In [2]:
data = pd.read_csv('Multiple linear regression  by sklearn.csv')

data.head(3)

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52
2  1760           3  2.54

## Create the multiple linear regression

In [3]:
x = data[['SAT','Rand 1,2,3']]

y = data['GPA']

In [4]:
reg = LinearRegression()

reg.fit(x,y)

LinearRegression()

In [5]:
reg.coef_

array([ 0.00165354, -0.00826982])

In [6]:
reg.intercept_

0.29603261264909353

### Calculating the R-squared

In [7]:
reg.score(x,y)

0.4066811952814282

### Formula for Adjusted R squared

$$R^2_{adj.} = 1 - (1-R^2)\times\frac{n-1}{n-p-1}$$
where $n$ is the number of observations and $p$ is the number of features

In [8]:
x.shape

(84, 2)

In [9]:
r2 = reg.score(x,y)

n = x.shape[0]

p = x.shape[1]

adjusted_r2 = 1-(1-r2)*(n-1)/(n-p-1)

adjusted_r2

0.39203134825134

## Feature selection

In [10]:
from sklearn.feature_selection import f_regression

f_regression(x,y)

(array([56.04804786,  0.17558437]), array([7.19951844e-11, 6.76291372e-01]))

In [11]:
p_values = f_regression(x,y)[1]

p_values

array([7.19951844e-11, 6.76291372e-01])

In [12]:
p_values.round(3)

array([0.   , 0.676])

## Creating a summary table

In [13]:
reg_summary = pd.DataFrame(data = x.columns.values, columns=['Features'])

reg_summary

Features
0         SAT
1  Rand 1,2,3

In [14]:
reg_summary ['Coefficients'] = reg.coef_

reg_summary ['p-values'] = p_values.round(3)

reg_summary

Features  Coefficients  p-values
0         SAT      0.001654     0.000
1  Rand 1,2,3     -0.008270     0.676